DROP TABLE IF EXISTS public.inventory; -- Ensure no existing table is causing issues

CREATE TABLE public."inventory" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item BIGINT NULL, 
    owner UUID NULL,
    quantity DOUBLE PRECISION NULL,
    notes TEXT NULL,
    "parentItem" BIGINT NULL, -- Ensure column name is quoted consistently
    time_of_deploy TIMESTAMP WITH TIME ZONE NULL,
    anomaly BIGINT NULL
);

-- Add constraints separately to simplify debugging
ALTER TABLE public."inventory"
    ADD CONSTRAINT inventory_parentItem_fkey FOREIGN KEY ("parentItem") REFERENCES public."inventory" (id),
    ADD CONSTRAINT inventory_anomaly_fkey FOREIGN KEY (anomaly) REFERENCES public."anomalies" (id),
    ADD CONSTRAINT inventory_owner_fkey FOREIGN KEY (owner) REFERENCES public.profiles (id);
