create table
  public.anomalies (
    id bigint generated by default as identity,
    content text null,
    anomalytype text null,
    researcher text null,
    avatar_url text null,
    created_at timestamp with time zone not null default now(),
    deepnote text null,
    lightkurve text null,
    configuration jsonb null,
    "parentAnomaly" bigint null,
    constraint baseplanets_pkey primary key (id),
    constraint anomalies_parentAnomaly_fkey foreign key ("parentAnomaly") references anomalies (id)
  ) tablespace pg_default;