CREATE TABLE public.classifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    content TEXT NULL,
    author UUID NULL,
    anomaly BIGINT NULL,
    classificationType TEXT NULL,
    classificationConfiguration JSONB NULL,
    media JSON NULL,
    CONSTRAINT classifications_pkey PRIMARY KEY (id),
    CONSTRAINT classifications_anomaly_fkey FOREIGN KEY (anomaly) REFERENCES anomalies (id),
    CONSTRAINT classifications_author_fkey FOREIGN KEY (author) REFERENCES profiles (id)
) TABLESPACE pg_default;
