CREATE TABLE public.classifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    content CHARACTER VARYING NULL,
    author UUID NULL,
    anomaly BIGINT NULL,
    classificationType TEXT NULL,
    media JSON NULL,
    CONSTRAINT classifications_pkey PRIMARY KEY (id),
    CONSTRAINT classifications_anomaly_fkey FOREIGN KEY (anomaly) REFERENCES missions (id),
    CONSTRAINT classifications_author_fkey FOREIGN KEY (author) REFERENCES profiles (id)
) TABLESPACE pg_default;
